import re
import os
import glob

class SchemaAuditor:
    def __init__(self, migration_path):
        self.migration_path = migration_path
        self.tables = {} # table_name -> {columns: [], fkeys: [], indexes: [], rls_enabled: False}
        self.issues = []

    def audit(self):
        print(f"Auditing migrations in {self.migration_path}...")
        migration_files = sorted(glob.glob(os.path.join(self.migration_path, "*.sql")))
        
        for file_path in migration_files:
            with open(file_path, 'r') as f:
                content = f.read()
                self._parse_content(content)

        self._check_integrity()
        self._report()

    def _parse_content(self, content):
        # Very simplified parsing for common SQL patterns
        
        # Table creation
        table_matches = re.finditer(r"CREATE TABLE IF NOT EXISTS (?:public\.)?(\w+) \((.*?)\);", content, re.DOTALL | re.IGNORECASE)
        for match in table_matches:
            table_name = match.group(1).lower()
            body = match.group(2)
            if table_name not in self.tables:
                self.tables[table_name] = {"fkeys": [], "indexes": [], "rls_enabled": False}
            
            # Extract Foreign Keys
            col_fk_matches = re.findall(r"(\w+)\s+(?:UUID|INT|BIGINT|VARCHAR|TEXT)\s+REFERENCES", body, re.IGNORECASE)
            for col in col_fk_matches:
                if col.lower() not in self.tables[table_name]["fkeys"]:
                    self.tables[table_name]["fkeys"].append(col.lower())

        # External Constraints/Indices
        index_matches = re.findall(r"CREATE INDEX.*?ON (?:public\.)?(\w+)\((\w+)\)", content, re.IGNORECASE)
        for table, col in index_matches:
            t_name = table.lower()
            if t_name in self.tables:
                if col.lower() not in self.tables[t_name]["indexes"]:
                    self.tables[t_name]["indexes"].append(col.lower())
            else:
                # Track index even if table creation not seen yet
                self.tables[t_name] = {"fkeys": [], "indexes": [col.lower()], "rls_enabled": False}

        # RLS
        rls_matches = re.findall(r"ALTER TABLE (?:public\.)?(\w+) ENABLE ROW LEVEL SECURITY", content, re.IGNORECASE)
        for table in rls_matches:
            t_name = table.lower()
            if t_name in self.tables:
                self.tables[t_name]["rls_enabled"] = True
            else:
                self.tables[t_name] = {"fkeys": [], "indexes": [], "rls_enabled": True}

    def _check_integrity(self):
        for table, meta in self.tables.items():
            # Check 1: FK Indexing
            for fk in meta["fkeys"]:
                if fk not in meta["indexes"]:
                    self.issues.append(f"[PERFORMANCE] Table '{table}' has foreign key '{fk}' but no index. This will cause slow joins.")
            
            # Check 2: RLS
            if not meta["rls_enabled"]:
                # Ignore some basic meta tables if needed, but for AstraFlow, most should be scoped
                if table not in ["organizations", "connectors"]:
                    self.issues.append(f"[SECURITY] Table '{table}' does not have Row Level Security (RLS) enabled.")

    def _report(self):
        print("\n--- Database Integrity Audit Report ---")
        if not self.issues:
            print("SUCCESS: No major integrity issues found in migrations.")
        else:
            print(f"Found {len(self.issues)} potential issues:")
            for issue in self.issues:
                print(f"  - {issue}")
        print("---------------------------------------\n")

    def generate_fixes(self, output_file):
        fixes = ["-- Automated Fixes generated by SchemaAuditor", ""]
        
        # 1. Performance: Indices
        fixes.append("-- 1. Missing Indices for Foreign Keys")
        for table, meta in self.tables.items():
            for fk in meta["fkeys"]:
                if fk not in meta["indexes"]:
                    idx_name = f"idx_{table}_{fk}"
                    if len(idx_name) > 63: # Postgres limit
                        idx_name = f"idx_{hash(idx_name) % 1000000}"
                    fixes.append(f"CREATE INDEX IF NOT EXISTS {idx_name} ON public.{table}({fk});")
        
        fixes.append("\n-- 2. Global RLS Enforcement")
        for table, meta in self.tables.items():
            if not meta["rls_enabled"]:
                fixes.append(f"ALTER TABLE public.{table} ENABLE ROW LEVEL SECURITY;")
                
        with open(output_file, "w") as f:
            f.write("\n".join(fixes))
        print(f"SUCCESS: Hardening SQL generated at {output_file}")

if __name__ == "__main__":
    # Point to the supabase migrations folder
    path = os.path.abspath(os.path.join(os.getcwd(), "supabase", "migrations"))
    auditor = SchemaAuditor(path)
    auditor.audit()
    
    # Generate the collective hardening script
    fix_path = os.path.join(path, "20260311000600_database_hardening.sql")
    auditor.generate_fixes(fix_path)
