-- Automated Fixes generated by SchemaAuditor

-- 1. Missing Indices for Foreign Keys
CREATE INDEX IF NOT EXISTS idx_connections_organization_id ON public.connections(organization_id);
CREATE INDEX IF NOT EXISTS idx_pipelines_organization_id ON public.pipelines(organization_id);
CREATE INDEX IF NOT EXISTS idx_organization_users_organization_id ON public.organization_users(organization_id);
CREATE INDEX IF NOT EXISTS idx_organization_users_user_id ON public.organization_users(user_id);
CREATE INDEX IF NOT EXISTS idx_pipeline_configs_pipeline_id ON public.pipeline_configs(pipeline_id);
CREATE INDEX IF NOT EXISTS idx_jobs_pipeline_id ON public.jobs(pipeline_id);
CREATE INDEX IF NOT EXISTS idx_job_metrics_job_id ON public.job_metrics(job_id);
CREATE INDEX IF NOT EXISTS idx_validation_rules_pipeline_id ON public.validation_rules(pipeline_id);
CREATE INDEX IF NOT EXISTS idx_validation_results_job_id ON public.validation_results(job_id);
CREATE INDEX IF NOT EXISTS idx_alerts_organization_id ON public.alerts(organization_id);
CREATE INDEX IF NOT EXISTS idx_schema_metadata_connection_id ON public.schema_metadata(connection_id);
CREATE INDEX IF NOT EXISTS idx_table_metadata_connection_id ON public.table_metadata(connection_id);
CREATE INDEX IF NOT EXISTS idx_column_metadata_table_id ON public.column_metadata(table_id);

-- 2. Global RLS Enforcement